import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Sends the original image and a style prompt to Gemini to generate a new outfit.
 */
export const generateOutfitChange = async (
  base64Image: string,
  mimeType: string,
  promptText: string
): Promise<string> => {
  try {
    // Strip the data URL prefix (e.g., "data:image/png;base64,") if present
    const base64Data = base64Image.split(',')[1] || base64Image;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: `Change the person's clothing to: ${promptText}. 
            
            CRITICAL INSTRUCTIONS:
            1. Keep the face, hair, pose, hand gestures, body shape, and background EXACTLY the same.
            2. Only change the outfit/clothing.
            3. Do not crop or zoom the image.
            4. Maintain photorealistic lighting and textures matching the original image.
            5. Output only the modified image.`,
          },
        ],
      },
    });

    // Iterate through parts to find the image
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};